services:

  #Calculator Controller

  src.calculator.controller:
    class: src\Calculator\CalculatorController
    arguments:
      - @src.calculator.model.model
      - @src.calculator.view.view
      - @slim.slim.request

