services:

  #Calculator Controller

  src.calculator.controller:
    class: Calculator\CalculatorController
    arguments:
      - @src.calculator.model
      - @src.calculator.view
      - @slim.request

