services:

  templates:        {synthetic: true}

  slim.request:     {synthetic: true}

  twig.loader:
    class:  Twig_Loader_Filesystem
    arguments:
        - @templates

  twig.environment:
     class: Twig_Environment
     arguments:
        - @twig.loader


