services:

  #Calculator Model

  src.calculator.model.modelfactory:
    class: Calculator\Model\ModelFactory
    arguments:
      - @slim.request
  src.calculator.model.modelerrorfactory:
    class: Calculator\Model\ModelErrorFactory
    arguments:
      - @slim.request